
version: '2.1'

services:

    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            # The standard AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        networks:
            - local_network

    producer:
        build:
            context: producer/
            dockerfile: Dockerfile
        image: producer:latest
        depends_on: 
            - rabbitmq
        environment: 
            - PYTHONPATH=${PYTHONPATH}:/app/src/producer.py
            - AMQP_URL=amqp://xxalaqou:dQFGDDlp-pfhSolv57XHhVWeqmzcmD6l@crow.rmq.cloudamqp.com/xxalaqou
        networks:
            - local_network


    consumer:
        build:
            context: .
            dockerfile: consumer/Dockerfile
        image: consumer:latest
        volumes:
            - "./consumer:/app/consumer:rw"
        depends_on:
            - rabbitmq
        ports:
            - "5000:5000"
        environment:
            - PYTHONPATH=${PYTHONPATH}:/app/src/consumer.py
            - AMQP_URL=amqp://xxalaqou:dQFGDDlp-pfhSolv57XHhVWeqmzcmD6l@crow.rmq.cloudamqp.com/xxalaqou
        networks:
            - local_network

networks:
    # Declare our private network.  We must declare one for the magic
    # Docker DNS to work, but otherwise its default settings are fine.
    local_network: {}